use BeerGame;
-- MySQL Script generated by MySQL Workbench
-- Fri Aug 16 23:48:13 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `team_id` INT(11) NOT NULL,
  `product_name` VARCHAR(15) NOT NULL,
  `production_time` INT(11) NULL,
  `initinal_inbound_amount` INT(11) NULL,
  PRIMARY KEY (`team_id`, `product_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`team` (
  `team_id` INT(11) NOT NULL,
  `already_taken` TINYINT(4) NULL,
  `budget` INT(11) NULL,
  `cost_inbound_wh` INT(11) NULL,
  `cost_outbound_wh` INT(11) NULL,
  `cost_backlog` INT(11) NULL,
  PRIMARY KEY (`team_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`inbound`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`inbound` (
  `inbound_id` INT(11) NOT NULL,
  `round_number` INT(11) NOT NULL,
  `amount` INT(11) NOT NULL,
  `time_stamp` DATETIME NOT NULL,
  `to_team` INT(11) NOT NULL,
  `product_name` VARCHAR(15) NOT NULL,
  `from_team` INT(11) NOT NULL,
  PRIMARY KEY (`inbound_id`),
  CONSTRAINT `fk_inbound_product1`
    FOREIGN KEY (`product_name` , `to_team`)
    REFERENCES `mydb`.`product` (`product_name` , `team_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inbound_team1`
    FOREIGN KEY (`from_team`)
    REFERENCES `mydb`.`team` (`team_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_inbound_product1_idx` ON `mydb`.`inbound` (`product_name` ASC, `to_team` ASC) VISIBLE;

CREATE INDEX `fk_inbound_team1_idx` ON `mydb`.`inbound` (`from_team` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`production`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`production` (
  `production_id` INT(11) NOT NULL,
  `round_number` INT(11) NOT NULL,
  `amount` INT(11) NOT NULL,
  `total_production_time` INT(11) NOT NULL,
  `team_id` INT(11) NOT NULL,
  `product_name` VARCHAR(15) NOT NULL,
  `time_stamp` DATETIME NOT NULL,
  PRIMARY KEY (`production_id`),
  CONSTRAINT `fk_production_product1`
    FOREIGN KEY (`team_id` , `product_name`)
    REFERENCES `mydb`.`product` (`team_id` , `product_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_production_product1_idx` ON `mydb`.`production` (`team_id` ASC, `product_name` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`outbound`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`outbound` (
  `outbound_id` INT(11) NOT NULL,
  `round_number` INT(11) NOT NULL,
  `amount` INT(11) NOT NULL,
  `time_stamp` DATETIME NOT NULL,
  `from_team` INT(11) NOT NULL,
  `product_name` VARCHAR(15) NOT NULL,
  `to_team` INT(11) NOT NULL,
  PRIMARY KEY (`outbound_id`),
  CONSTRAINT `fk_outbound_product1`
    FOREIGN KEY (`from_team` , `product_name`)
    REFERENCES `mydb`.`product` (`team_id` , `product_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_outbound_team1`
    FOREIGN KEY (`to_team`)
    REFERENCES `mydb`.`team` (`team_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_outbound_product1_idx` ON `mydb`.`outbound` (`from_team` ASC, `product_name` ASC) VISIBLE;

CREATE INDEX `fk_outbound_team1_idx` ON `mydb`.`outbound` (`to_team` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orders` (
  `order_id` INT(11) NOT NULL,
  `round_number` INT(11) NOT NULL,
  `amount` INT(11) NOT NULL,
  `time_stamp` DATETIME NOT NULL,
  `from_team` INT(11) NOT NULL,
  `product_name` VARCHAR(15) NOT NULL,
  `to_team` INT(11) NOT NULL,
  PRIMARY KEY (`order_id`),
  CONSTRAINT `fk_orders_product1`
    FOREIGN KEY (`from_team` , `product_name`)
    REFERENCES `mydb`.`product` (`team_id` , `product_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_team1`
    FOREIGN KEY (`to_team`)
    REFERENCES `mydb`.`team` (`team_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_orders_product1_idx` ON `mydb`.`orders` (`from_team` ASC, `product_name` ASC) VISIBLE;

CREATE INDEX `fk_orders_team1_idx` ON `mydb`.`orders` (`to_team` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`rounds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rounds` (
  `round_number` INT NOT NULL,
  `round_duration_fixed` INT(11) NOT NULL,
  `start_time_actual` DATETIME NULL,
  `end_time_actual` DATETIME NULL,
  PRIMARY KEY (`round_number`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
